# Generated by Django 5.0.6 on 2026-03-13 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('rent_reminder', 'Rent Reminder'), ('lease_expiry', 'Lease Expiry Warning'), ('general', 'General Notice'), ('maintenance', 'Maintenance Notice'), ('eviction_warning', 'Eviction Warning'), ('welcome', 'Welcome')], max_length=30)),
                ('audience_type', models.CharField(choices=[('single_tenant', 'Single Tenant'), ('unit', 'Single Unit'), ('floor', 'Entire Floor'), ('property', 'Entire Property'), ('all', 'All Tenants in Org')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('body_nepali', models.TextField(blank=True)),
                ('sent_by_user_id', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channels', models.JSONField(default=list)),
                ('delivery_status', models.JSONField(default=dict)),
                ('target_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='properties.property')),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='tenancies.tenant')),
            ],
        ),
    ]
