# Generated by Django 5.0.6 on 2026-03-13 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_nepali', models.CharField(blank=True, max_length=200)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use'), ('hostel', 'Hostel/PG')], max_length=20)),
                ('ward_no', models.CharField(max_length=10)),
                ('municipality', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('google_maps_url', models.URLField(blank=True)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField(default=0)),
                ('unit_type', models.CharField(choices=[('flat', 'Flat/Apartment'), ('room_single', 'Single Room'), ('room_double', 'Double Room'), ('commercial_stall', 'Commercial Stall'), ('shop', 'Shop'), ('storage', 'Storage Unit'), ('hostel_bed', 'Hostel Bed'), ('floor', 'Entire Floor')], max_length=30)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_rent_npr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_npr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='vacant', max_length=20)),
                ('amenities', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'ordering': ['floor', 'unit_number'],
                'unique_together': {('property', 'unit_number')},
            },
        ),
    ]
