# Generated by Django 5.0.6 on 2026-03-13 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('full_name_nepali', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('citizenship_number', models.CharField(max_length=50, unique=True)),
                ('citizenship_front', models.CharField(blank=True, max_length=500)),
                ('citizenship_back', models.CharField(blank=True, max_length=500)),
                ('date_of_birth_bs', models.CharField(blank=True, max_length=10)),
                ('date_of_birth_ad', models.DateField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('portal_activated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_bs', models.CharField(max_length=10)),
                ('end_date_bs', models.CharField(max_length=10)),
                ('start_date_ad', models.DateField()),
                ('end_date_ad', models.DateField()),
                ('rent_npr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_npr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_due_day', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('month_to_month', 'Month to Month')], default='draft', max_length=20)),
                ('lease_document', models.CharField(blank=True, max_length=500)),
                ('tenant_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='tenancies.tenant')),
            ],
            options={
                'ordering': ['-start_date_ad'],
            },
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role', models.CharField(choices=[('owner', 'Corporate Owner'), ('manager', 'Property Manager'), ('caretaker', 'Caretaker'), ('tenant', 'Tenant')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_properties', models.ManyToManyField(blank=True, related_name='assigned_managers', to='properties.property')),
                ('assigned_units', models.ManyToManyField(blank=True, related_name='assigned_caretakers', to='properties.unit')),
            ],
            options={
                'unique_together': {('user_id', 'role')},
            },
        ),
    ]
