# Generated by Django 5.0.6 on 2026-03-13 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('due_7_days', '7 days before due'), ('due_today', 'Due today'), ('overdue_3', '3 days overdue'), ('overdue_7', '7 days overdue'), ('manual', 'Manual')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('app', 'In-app')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('message_preview', models.TextField(blank=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancies.lease')),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_npr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_month_bs', models.CharField(max_length=7)),
                ('period_month_ad', models.DateField()),
                ('method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=200)),
                ('paid_at_bs', models.CharField(blank=True, max_length=10)),
                ('paid_at_ad', models.DateTimeField(blank=True, null=True)),
                ('logged_by_user_id', models.IntegerField()),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_document', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancies.lease')),
            ],
        ),
    ]
