# Generated by Django 5.0.6 on 2026-03-13 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('registered', 'Registered'), ('renewal_required', 'Renewal Required'), ('expired', 'Expired')], default='not_started', max_length=30)),
                ('ward_police_office', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('registered_date_bs', models.CharField(blank=True, max_length=10)),
                ('registered_date_ad', models.DateField(blank=True, null=True)),
                ('expiry_date_ad', models.DateField(blank=True, null=True)),
                ('form_document', models.CharField(blank=True, max_length=500)),
                ('confirmation_document', models.CharField(blank=True, max_length=500)),
                ('api_submission_id', models.CharField(blank=True, max_length=200)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_reg', to='tenancies.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancies.tenant')),
            ],
        ),
    ]
